sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    rust:
      - nightly
  exclude:
    rust:
      - nightly
    script:
      - cargo bench
  fast_finish: true
# the main build
script:
  - cargo build
  - cargo test
  - cargo bench
cache: cargo
