sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
# unit and benchmark tests
script:
  - cargo test
  - cargo bench
matrix:
  allow_failures:
    rust:
      - nightly
  fast_finish: true

cache: cargo
