[package]
name = "rksuid"
version = "0.2.1"
authors = ["nharring@gmail.com"]
edition = "2018"
description="Rust implementation of the Segment.io KSUID format"
repository="https://github.com/nharring/rksuid"
readme="README.md"
license="MIT"
keywords=["ksuid", "uuid"]


[badges]
travis-ci = {repository="nharring/rksuid", branch="master"}
codecov = { repository = "nharring/rksuid", branch = "master", service = "github" }
maintenance = {status="actively-developed"}

[dependencies]
base-encode = "0.3.0"
rand = "0.7.0"
chrono = "0.4"
time = "0.1"
arrayref = "0.3.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "rksuid_criterion"
harness = false
